### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by mayvyle** [jeffreytram/UniDrive#169]
**Describe the bug**
Date works fine. Search still does not. Safari Issue ONLY.

**To Reproduce**
1. Go to application.
2. Try Search.
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: Safari Issue ONLY.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jeffreytram** [comment]
Duplicated issue #135
